### ISSUE TITLE
Lab 1: Hello World!

### ISSUE THREAD

**Issue by EBUJOLD** [nickcounts/Arduino-Lessons#19]

**Comment by jtsingh7** [comment]
pushed my edits so I think it looks good. don't think we need anymore pics or gifs here

**Comment by jtsingh7** [comment]
did the lab myself and found some solutions to troubleshooting problems and a typo in the code. Could use a final set of eyes before its ready

**Comment by jtsingh7** [comment]
added a deeper understanding section that just covered how LED screens work. rough draft

**Comment by nickcounts** [comment]
Looks great! I just have a couple of thoughts:

"The processor is preinstalled with a "Hello World" program" - is that true? It'd be awesome if it is, but you might have just been seeing that because it's the last thing I did with the guys here?

Should we include explicit steps to start a new program in the first tutorial? Something like:
>  Click `File` and `New` to start a new program. 

Do we want to talk at all about what 'OD01' is in the code - We don't have to explain controller objects and classes, maybe just something about passing "print" or "clear" messages to the chip? I'm easy on this either way

**Comment by EBUJOLD** [comment]
Jake, did you push your deeper understanding? I don't have it

**Comment by jtsingh7** [comment]
weird, I pushed it yesterday but I didn't see it on the wiki page either. I just added it directly to the wiki so it's there now

**Comment by nickcounts** [comment]
Great writeup, Jake - every time I thought "oh, we need to tell them about this" you did it in the next sentence.  Crushed it. 

My only nitpick is that I'm on a personal crusade to abolish the word "utilize" 😜

I leave use/utilize up to you both to decide

**Comment by jtsingh7** [comment]
yeah utilize is a dumb word. it's been changed to "use"

**Comment by EBUJOLD** [comment]
is this ready for release?
